"""
Report Generator — Produce professional Markdown intelligence briefs.

Converts agent output (search results + AI analysis + optional visualization)
into structured, readable reports with full audit trail.
"""

import logging
from datetime import datetime, timezone
from typing import Optional
from pathlib import Path

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generate Markdown intelligence reports from agent output."""

    def __init__(self, output_dir: Path = Path("examples")):
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(self, result) -> str:
        """Generate a complete intelligence report from an IntelligenceResult.

        Args:
            result: IntelligenceResult from the engine run

        Returns:
            Path to the generated report file
        """
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H%M%SZ")
        safe_topic = "".join(c if c.isalnum() else "-" for c in result.query)[:40]
        filename = f"intel-brief-{safe_topic}-{timestamp}.md"
        filepath = self.output_dir / filename

        lines = [
            f"# 🔮 Atlas Nexus Intelligence Brief",
            f"",
            f"**Topic**: {result.query}",
            f"**Generated**: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
            f"**Agent**: Autonomous Data Intelligence Agent — OOBE Synapse × Ace Data Cloud",
            f"",
            f"---",
            f"",
            f"## 🧠 AI Analysis",
            f"",
            result.ai_analysis,
            f"",
        ]

        if result.visualization_url:
            lines.extend([
                f"---",
                f"",
                f"## 🎨 Visualization",
                f"",
                f"![Generated visualization]({result.visualization_url})",
                f"",
            ])

        # Execution audit trail
        lines.extend([
            f"---",
            f"",
            f"## 🔍 Execution Audit",
            f"",
            f"### Services Used (Ace Data Cloud via x402)",
            f"",
            *[f"- ✅ **{svc}** — Ace Data Cloud API" for svc in result.services_used],
            f"",
            f"### Payment Summary",
            f"",
            f"- **Total USDC spent**: ${result.total_cost_usdc:.6f}",
            f"- **Payment protocol**: x402 (Solana)",
            f"",
            f"### Run Log",
            f"",
            *[f"- {entry}" for entry in result.run_log],
            f"",
            f"---",
            f"",
            f"*Autonomously generated by Atlas Nexus Data Intelligence Agent*",
            f"*Powered by OOBE Protocol Synapse × Ace Data Cloud × x402*",
        ])

        report = "\n".join(lines)
        filepath.write_text(report)
        logger.info(f"📄 Report generated: {filepath}")
        return str(filepath)


class DemoScriptGenerator:
    """Generate a markdown demo script documenting the complete workflow."""

    def generate(self, agent_name: str, sample_query: str, run_log: dict) -> str:
        """Create demo walkthrough for bounty submission.

        Args:
            agent_name: Agent display name
            sample_query: Example query used in demo
            run_log: Dictionary with 'services', 'total_cost', 'steps'
        """
        lines = [
            f"# 🔮 Demo: Autonomous Data Intelligence Agent",
            f"",
            f"## Agent Identity",
            f"- **Name**: {agent_name}",
            f"- **Platform**: OOBE Synapse Agent Protocol (SAP)",
            f"- **Infrastructure**: Ace Data Cloud (3 services) + x402 payments",
            f"",
            f"## Workflow",
            f"",
            f"### 1️⃣ Agent Registration on SAP",
            f"Agent registered on-chain via Synapse Agent Protocol.",
            f"Capabilities: search, analysis, visualization.",
            f"",
            f"### 2️⃣ Tool Discovery",
            f"Agent discovers Ace Data Cloud services through SAP:",
            f"- `acedatacloud-search` — real-time web search",
            f"- `acedatacloud-chat` — AI-powered analysis",
            f"- `acedatacloud-images` — visualization generation",
            f"",
            f"### 3️⃣ Data Collection → Search",
            f"**Query**: *{sample_query}*",
            f"**Service**: Ace Data Cloud Search",
            f"**Payment**: x402 (Solana USDC)",
            f"",
            f"### 4️⃣ AI Analysis → Chat",
            f"**Service**: Ace Data Cloud Chat (gpt-4o-mini)",
            f"**Input**: Raw search results",
            f"**Output**: Structured intelligence analysis",
            f"**Payment**: x402 (Solana USDC)",
            f"",
            f"### 5️⃣ Report Generation",
            f"Markdown intelligence brief with:",
            f"- AI analysis section",
            f"- Execution audit trail",
            f"- Payment reconciliation",
            f"",
            f"## ✅ Bounty Requirements",
            f"",
            f"- [x] Agent registered on Synapse Agent Protocol",
            f"- [x] Complete automated workflow executed",
            f"- [x] Ace Data Cloud account created/used",
            f"- [x] x402 with Ace Data Cloud facilitator + Synapse RPC",
            f"- [x] **3 distinct Ace Data Cloud services**: Search, Chat, Images",
            f"- [x] GitHub repository",
            f"- [ ] Demo published on X (@OOBEonSol @AceDataCloud)",
            f"",
            f"## 💰 Payment Audit",
            f"",
            *[f"- **{s['name']}**: {s['calls']} call(s) — ~${s['cost']:.4f} USDC"
              for s in run_log.get('services_detail', [])],
            f"",
            f"**Total**: ${run_log.get('total_cost', 0):.6f} USDC via x402 (Solana)",
            f"",
            f"---",
            f"*Demo prepared for OOBE × Ace Data Cloud Autonomous Agent Bounty*",
        ]
        return "\n".join(lines)
