/**
 * Autonomous Workflow Engine
 *
 * Orchestrates: Search → Analyze → Visualize → Report
 * All 3 Ace Data Cloud services + x402 payment tracking.
 */

import { AceDataCloudServices } from './ace-bridge.js';
import { writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

export interface WorkflowResult {
  query: string;
  timestamp: string;
  searchResults: string;
  aiAnalysis: string;
  visualizationUrl: string | null;
  servicesUsed: string[];
  totalCostUsdc: number;
  steps: string[];
  reportPath: string;
}

export class WorkflowEngine {
  private services: AceDataCloudServices;

  constructor(services: AceDataCloudServices) {
    this.services = services;
  }

  async execute(query: string, generateImage = false): Promise<WorkflowResult> {
    const steps: string[] = [];
    const log = (msg: string) => {
      const ts = new Date().toISOString().slice(11, 19);
      const entry = `[${ts}] ${msg}`;
      console.log(entry);
      steps.push(entry);
    };

    log(`🚀 Starting intelligence run: "${query}"`);

    // Step 1: Data Collection — Ace Data Cloud Search
    log('Step 1/3: Ace Data Cloud Search...');
    const searchResults = await this.services.search(query);
    log(`  Done (${searchResults.length} chars)`);

    // Step 2: AI Analysis — Ace Data Cloud Chat
    log('Step 2/3: Ace Data Cloud Chat analysis...');
    const aiAnalysis = await this.services.analyze(searchResults);
    log(`  Done (${aiAnalysis.length} chars)`);

    // Step 3: Visualization — Ace Data Cloud Images
    let visualizationUrl: string | null = null;
    if (generateImage) {
      log('Step 3/3: Ace Data Cloud Images...');
      visualizationUrl = await this.services.visualize(
        `Crypto intelligence infographic: ${query}, dark theme, data visualization, professional`
      );
      log(`  ${visualizationUrl ? 'Generated' : 'Skipped'}`);
    } else {
      log('Step 3/3: Skipped (use --image to enable)');
    }

    // Generate Report
    log('📄 Generating intelligence report...');
    const reportPath = this._writeReport({
      query,
      searchResults,
      aiAnalysis,
      visualizationUrl,
      steps,
    });
    log(`✅ Report: ${reportPath}`);

    return {
      query,
      timestamp: new Date().toISOString(),
      searchResults,
      aiAnalysis,
      visualizationUrl,
      servicesUsed: this.services.tracker.serviceNames,
      totalCostUsdc: this.services.tracker.totalUsdc,
      steps,
      reportPath,
    };
  }

  private _writeReport(data: {
    query: string;
    searchResults: string;
    aiAnalysis: string;
    visualizationUrl: string | null;
    steps: string[];
  }): string {
    const ts = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const safeTopic = data.query.replace(/[^a-zA-Z0-9]/g, '-').slice(0, 40);
    const filename = `intel-brief-${safeTopic}-${ts}.md`;

    const outDir = resolve(process.cwd(), 'examples');
    mkdirSync(outDir, { recursive: true });
    const filepath = resolve(outDir, filename);

    const usage = this.services.tracker.summary();
    const lines = [
      '# 🔮 Atlas Nexus Intelligence Brief',
      '',
      `**Topic**: ${data.query}`,
      `**Generated**: ${new Date().toISOString()}`,
      `**Agent**: AtlasNexusDataIntel — OOBE Synapse × Ace Data Cloud`,
      '',
      '---',
      '',
      '## 🧠 AI Analysis',
      '',
      data.aiAnalysis,
      '',
    ];

    if (data.visualizationUrl) {
      lines.push('---', '', '## 🎨 Visualization', '', `![](${data.visualizationUrl})`, '');
    }

    lines.push(
      '---',
      '',
      '## 🔍 Execution Audit',
      '',
      '### Ace Data Cloud Services (via x402)',
      '',
    );
    for (const s of usage) {
      lines.push(`- ✅ **${s.service}** — ${s.calls} call(s), ~$${s.estimatedCostUsdc.toFixed(4)} USDC`);
    }

    lines.push(
      '',
      `**Total**: $${this.services.tracker.totalUsdc.toFixed(6)} USDC via x402 (Solana)`,
      '',
      '### Run Log',
      '',
    );
    for (const s of data.steps) {
      lines.push(`- ${s}`);
    }

    lines.push(
      '',
      '---',
      '',
      '*Autonomously generated by Atlas Nexus Data Intelligence Agent*',
      '*OOBE Synapse × Ace Data Cloud × x402 Payments*',
    );

    writeFileSync(filepath, lines.join('\n'));
    return filepath;
  }
}
